
name: Cache Example

on:
  workflow_dispatch:

jobs:
  cache-demo:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: prime-cache-d63003d
        id: cache_step
        uses: actions/cache@v4
        with:
          path: |
            ~/.cache/pip
            .venv
          key: cache-d63003d
      - name: Show cache result
        run: echo "Cache result:${{ steps.cache_step.outputs.cache-hit }}"
      - name: 25ds3000144@ds.study.iitm.ac.in
        run: echo "This is a step with my email address."
